### ISSUE TITLE
Allow creating Kaitai::Struct::Stream from StringIO (not just String)

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct_ruby_runtime#10]
This code:

```ruby
require 'stringio'
require_relative 'lib/kaitai/struct/struct'

io = Kaitai::Struct::Stream.new(StringIO.new("PK\x03\x04"))
```

currently fails with

```console
$ ruby t.rb
C:/temp/kaitai_struct/runtime/ruby/lib/kaitai/struct/struct.rb:104:in `initialize': can be initialized with IO, SubIO or String only (TypeError)
        from t.rb:4:in `new'
        from t.rb:4:in `<main>'
```

because the `Stream.new` implementation expects to recieve a plain `String` instead:

```ruby
io = Kaitai::Struct::Stream.new("PK\x03\x04")
```

and it will create a `StringIO` itself:

https://github.com/kaitai-io/kaitai_struct_ruby_runtime/blob/515d34dc7d7c58d6ad997a761234638d37925267/lib/kaitai/struct/struct.rb#L97-L104

I think rejecting the accepted `StringIO` and insisting on creating it "automatically" is an unnecessary restriction, and initialization with `StringIO` should be allowed as well to make it foolproof.

**Comment by GreyCat** [comment]
Interesting... I've never realized that StringIO is not derived from IO in Ruby. I've tried to fix it.
